devices([
   	"iPad (7th generation)",
	"iPhone 8 Plus",
	"iPad Pro (11-inch) (2nd generation)",
	"iPad Pro (12.8-inch) (4th generation)",
	"iPhone 8",
	"iPhone 8 Plus",
	"iPhone 11",
	"iPhone 11 Pro",
	"iPhone 11 Pro Max",
])

languages([
  "en-US"
])

scheme "GravityGolfScreenshots-iOS"

clear_previous_screenshots false

project "./Gravity Golf.xcodeproj"